language: c
sudo: required
services:
  - docker
env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION="6.3"
    - RACKET_VERSION="6.4"
before_install:
  - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
  - cat ../travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"
  - docker pull jackfirth/racket
install:
  - raco pkg install --auto $TRAVIS_BUILD_DIR/herbie
  - docker build .
script:
  - raco test herbie
  - racket herbie/reports/travis.rkt bench/tutorial.rkt bench/hamming/
notifications:
  slack:
    secure: QB8ib/gxZWZ8rY9H54BktIgx8LfjdqabSAkmWip0VHlUhrh2ULG566XgmB5h75eNzCil2cw76ma5wfSC0MNIQ1iDHKCxAgTE0+gcPcZAYGfucQ28sKGBG2wcuJfvBLG6lVDxj+luGUh3XohouTLYI9cg509JBgTgpcrXVexYAaE=
