language: c
sudo: false

env:
  - RACKET_DIR=~/racket

# Uses Racket 6.1.1
before_install:
  - curl -L -o racket-install.sh http://mirror.racket-lang.org/installers/6.1.1/racket-6.1.1-x86_64-linux-debian-squeeze.sh
  - sh racket-install.sh --in-place --dest ~/racket

script:
  - ~/racket/bin/racket herbie/reports/run.rkt -p bench/hamming
