language: c
sudo: false
env:
- RACKET_DIR=~/racket
before_install:
- curl -L -o racket-install.sh http://mirror.racket-lang.org/installers/6.4/racket-6.4-x86_64-linux-debian-squeeze.sh
- sh racket-install.sh --in-place --dest ~/racket
script:
- "~/racket/bin/racket herbie/herbie.rkt --test bench/tutorial.rkt bench/hamming/"
notifications:
  slack:
    secure: QB8ib/gxZWZ8rY9H54BktIgx8LfjdqabSAkmWip0VHlUhrh2ULG566XgmB5h75eNzCil2cw76ma5wfSC0MNIQ1iDHKCxAgTE0+gcPcZAYGfucQ28sKGBG2wcuJfvBLG6lVDxj+luGUh3XohouTLYI9cg509JBgTgpcrXVexYAaE=
