language: c
sudo: required
env:
  global:
    - RACKET_DIR=~/racket
      HERBIE_SEED="#(2749829514 1059579101 312104142 915324965 966790849 1349306526)"
      TTEST="racket $TRAVIS_BUILD_DIR/infra/travis.rkt --seed '${HERBIE_SEED}' bench/tutorial.fpcore bench/hamming/"
      TTEST_RAND="racket $TRAVIS_BUILD_DIR/infra/travis.rkt bench/tutorial.fpcore bench/hamming/"
      UTEST="raco test src"
  matrix:
    # separate builds for unit tests and hamming tests
    - RACKET_VERSION="6.7"
      JOB="${TTEST}"
    - RACKET_VERSION="6.9"
      JOB="${TTEST}"
    - RACKET_VERSION="6.11"
      JOB="${TTEST}"
    - RACKET_VERSION="6.7"
      JOB="${UTEST}"
    - RACKET_VERSION="6.9"
      JOB="${UTEST}"
    - RACKET_VERSION="6.11"
      JOB="${UTEST}"
    # remember to change the `allow_failures` key below!
    - RACKET_VERSION="6.11"
      JOB="${TTEST_RAND}"
matrix:
  allow_failures:
    - env: RACKET_VERSION="6.11"
           JOB="${TTEST_RAND}"
before_install:
  - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
  - cat ../travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"
install:
  - raco pkg install --auto $TRAVIS_BUILD_DIR/src
script:
  - echo ${JOB} && eval ${JOB}
notifications:
  slack:
    secure: QB8ib/gxZWZ8rY9H54BktIgx8LfjdqabSAkmWip0VHlUhrh2ULG566XgmB5h75eNzCil2cw76ma5wfSC0MNIQ1iDHKCxAgTE0+gcPcZAYGfucQ28sKGBG2wcuJfvBLG6lVDxj+luGUh3XohouTLYI9cg509JBgTgpcrXVexYAaE=
