language: c
sudo: false

env:
  - RACKET_DIR=~/racket

# Uses Racket 6.1.1
before_install:
  - curl -L -o racket-install.sh http://download.racket-lang.org/installers/6.1.1/racket/racket-6.1.1-bin-x86_64-linux-debian-squeeze.sh
  - printf "no\n6.1.1\n" | sh racket-install.sh

script:
  - racket herbie/reports/run.rkt bench/hamming